#!/bin/bash

loggedInUser=$(/bin/echo "show State:/Users/ConsoleUser" | /usr/sbin/scutil | /usr/bin/awk '/Name :/&&!/loginwindow/{print $3}')
loggedInUID=`id -u ${loggedInUser}`

if [[ ${loggedInUID} -gt 500 ]]; then
	echo "Launching SplashBuddy for user ${loggedInUID}…"
	sudo -u \#${loggedInUID} launchctl enable gui/${loggedInUID}/io.fti.SplashBuddy.launch
	sudo -u \#${loggedInUID} launchctl bootstrap gui/${loggedInUID}/ /Library/LaunchAgents/io.fti.SplashBuddy.launch.plist
	sudo -u \#${loggedInUID} launchctl kickstart gui/${loggedInUID}/io.fti.SplashBuddy.launch
fi

